R_CONST = 8.3144621  # Gas constant
G_X = 1  # x_H of GAS (usually 1)
ACC = 1e-4  # accuracy when finding common
SLICES = 20
DX = 1e-5  # change when going away from IP
DX1 = 1e-6  # First derivate accuracy
DX2 = 1e-5  # Second derivate accuracy
WEIGHT = 3  # weight of plateau information over normal p_x pairs
BOUND_MAX = 0
SLOPE_MIN = -100000
SLOPE_MAX = 100000
P_MAX = 1e19
D_X = 0.01  # uncertainty for composition points
